import './style.css';
import { blankPacket, type Medication, type Packet, type Question, type SourceItem } from './types';
import { decryptBundle, encryptBundle, type EncryptedBundle } from './crypto';

const DB = 'health-visit-packet'; const STORE = 'packet'; const KEY = 'current';
let packet = blankPacket(); let saveTimer = 0;
const LICENSE_KEY = 'sb_license:health-visit-packet'; const VERDICT_KEY = `${LICENSE_KEY}:verdict`;
let plus = false;
const $ = <T extends Element>(s: string) => document.querySelector<T>(s)!;
const uid = () => crypto.randomUUID();
const esc = (s: string) => s.replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]!));
function openDB(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const r = indexedDB.open(DB, 1); r.onupgradeneeded = () => r.result.createObjectStore(STORE); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); }
async function load() { try { const db = await openDB(); const p = await new Promise<Packet | undefined>((resolve, reject) => { const r = db.transaction(STORE).objectStore(STORE).get(KEY); r.onsuccess=()=>resolve(r.result); r.onerror=()=>reject(r.error); }); if (p?.version === 1) { packet = p; packet.profile.coverNote ??= ''; } } catch { announce('Your browser could not open its private storage. Keep this tab open and export a backup.'); } }
function queueSave() { packet.updatedAt = new Date().toISOString(); clearTimeout(saveTimer); saveTimer = window.setTimeout(async () => { try { const db = await openDB(); db.transaction(STORE, 'readwrite').objectStore(STORE).put(packet, KEY); setSave('Saved on this device'); } catch { setSave('Could not save locally'); } }, 250); }
function setSave(message: string) { const e = document.querySelector('#save-state'); if (e) e.textContent = message; }
function announce(message: string) { const e = document.querySelector('#notice'); if (e) e.textContent = message; }
function download(name: string, body: string) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([body], { type: 'application/json' })); a.download=name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
const input = (label: string, name: string, value = '', type = 'text', required = false) => `<label>${label}${required ? ' <span aria-hidden="true">*</span>' : ''}<input ${required ? 'required' : ''} type="${type}" name="${name}" value="${esc(value)}"></label>`;
function sourceHtml(o: SourceItem) { return `<li class="paper-item"><div><strong>${esc(o.label)}</strong><span class="value">${esc(o.value)} ${esc(o.unit)}</span></div><div class="meta">${esc(o.source)} · ${esc(o.date || 'date not recorded')}${o.note ? ` · ${esc(o.note)}` : ''}</div><button class="quiet delete" data-kind="observations" data-id="${o.id}" aria-label="Remove ${esc(o.label)}">Remove</button></li>`; }
function renderPacket() {
  const p = packet.profile;
  $('#packet-sheet').innerHTML = `<div class="packet-cap"><span>Prepared visit packet</span><span>${p.appointmentDate ? esc(p.appointmentDate) : 'date not set'}</span></div>
  <h2>${p.name ? esc(p.name) + '’s packet' : 'Your visit packet'}</h2>
  <p class="packet-reason">${p.reason ? esc(p.reason) : 'Add what you want to cover at this visit.'}${p.clinician ? ` <span>For ${esc(p.clinician)}</span>` : ''}</p>
  ${plus && p.coverNote ? `<aside class="cover-note"><b>Personal cover note</b><br>${esc(p.coverNote)}</aside>` : ''}
  ${sectionPreview('Selected results & observations', packet.observations.map(sourceHtml).join(''), 'No source-labeled results yet.')}
  ${sectionPreview('Medicines', packet.medications.map(m => `<li class="paper-item"><strong>${esc(m.name)}</strong><span>${esc(m.dose)}${m.schedule ? ` · ${esc(m.schedule)}` : ''}</span><small>Source: ${esc(m.source)}</small><button class="quiet delete" data-kind="medications" data-id="${m.id}" aria-label="Remove ${esc(m.name)}">Remove</button></li>`).join(''), 'No medicines added.')}
  ${sectionPreview('Questions for this visit', packet.questions.map((q,i) => `<li class="question"><b>${i+1}.</b> ${esc(q.question)}${q.note ? `<small>${esc(q.note)}</small>` : ''}<button class="quiet delete" data-kind="questions" data-id="${q.id}" aria-label="Remove question ${i+1}">Remove</button></li>`).join(''), 'No questions added.')}
  <p class="packet-foot">Personal record prepared by you. Values are copied as entered; this is not medical advice.</p>`;
  bindDeletes();
}
function sectionPreview(title: string, items: string, empty: string) { return `<section class="print-section"><h3>${title}</h3>${items ? `<ul>${items}</ul>` : `<p class="empty-inline">${empty}</p>`}</section>`; }
function render() {
  $('#app').innerHTML = `<header class="site-header"><a class="wordmark" href="/" aria-label="Health Visit Packet home"><span class="mark" aria-hidden="true"></span>Health Visit Packet</a><nav aria-label="Utility"><span id="save-state" role="status">Stored only on this device</span><a href="/privacy">Privacy</a></nav></header>
  <main id="main"><section class="intro"><div><p class="eyebrow">A private pre-visit workspace</p><h1>Bring one clear page to your next appointment.</h1><p class="lede">Collect only the medicines, values, source dates, questions, and observations that matter. Everything stays in this browser unless you export it.</p><a class="jump" href="#editor">Start your packet <span aria-hidden="true">↓</span></a></div><figure><img src="/packet-diorama.webp" width="768" height="512" fetchpriority="high" decoding="async" alt="Paper-cut illustration of a visit packet with blank lab slips, a medicine bottle, pencil, and question card."><figcaption>Original generated illustration · no records leave your device.</figcaption></figure></section>
  <div class="offline" id="offline" hidden role="status">You’re offline. Your packet is still available here.</div><p id="notice" class="sr-only" role="status" aria-live="polite"></p>
  <section id="editor" class="workspace" aria-label="Packet editor"><aside class="editor"><div class="editor-head"><p class="eyebrow">Build your packet</p><p>Fields marked <span aria-hidden="true">*</span> help you keep the record traceable.</p></div>
  <details open><summary>Visit details</summary><form id="profile-form" class="field-grid">${input('Your name', 'name', packet.profile.name)}${input('Appointment date', 'appointmentDate', packet.profile.appointmentDate, 'date')}${input('Clinician or clinic', 'clinician', packet.profile.clinician)}<label>What do you want to cover?<textarea name="reason" rows="3">${esc(packet.profile.reason)}</textarea></label>${plus ? `<label>Personal cover note <textarea name="coverNote" rows="3">${esc(packet.profile.coverNote || '')}</textarea></label>` : ''}</form></details>
  <details open><summary>Results & observations <span class="count">${packet.observations.length}</span></summary><form id="observation-form" class="entry-form">${input('Result or observation', 'label', '', 'text', true)}<div class="two-up">${input('Value', 'value', '', 'text', true)}${input('Unit (optional)', 'unit')}</div>${input('Where did this come from?', 'source', '', 'text', true)}${input('Date from source', 'date', '', 'date')}<label>Context or note (optional)<textarea name="note" rows="2"></textarea></label><button class="secondary" type="submit">Add result</button></form></details>
  <details><summary>Medicines <span class="count">${packet.medications.length}</span></summary><form id="medication-form" class="entry-form">${input('Medicine name', 'name', '', 'text', true)}<div class="two-up">${input('Dose', 'dose', '', 'text', true)}${input('Schedule', 'schedule')}</div>${input('Source (label, bottle, portal)', 'source', '', 'text', true)}<button class="secondary" type="submit">Add medicine</button></form></details>
  <details><summary>Questions <span class="count">${packet.questions.length}</span></summary><form id="question-form" class="entry-form"><label>Question for the clinician <textarea required name="question" rows="3"></textarea></label><label>Why it matters (optional)<input name="note"></label><button class="secondary" type="submit">Add question</button></form></details>
  <section class="export-panel"><p class="eyebrow">Take it with you</p><p>Review the visible sheet before printing. Include only what you’re comfortable handing over.</p><button id="print" class="primary">Print or save as PDF</button><button id="encrypted-export" class="secondary">Download encrypted bundle</button><button id="json-export" class="text-button">Download plain JSON</button><label class="import-label">Restore encrypted bundle<input id="import-file" type="file" accept="application/json"></label></section></aside>
  <section class="preview-area" aria-label="Packet preview"><div class="preview-label"><span>Live packet preview</span><span>Review before printing</span></div><article id="packet-sheet" tabindex="-1"></article></section></section>
  <section class="trust"><h2>Your data stays close.</h2><div><p><b>Local by default.</b> We use this browser’s private storage—no account, tracker, or cloud record.</p><p><b>Source-labelled.</b> Keep the where and when beside every selected value.</p><p><b>Portable on purpose.</b> Print a paper/PDF handoff or save an encrypted bundle you can restore later.</p></div></section><section class="plus-panel"><div><p class="eyebrow">Optional one-time unlock</p><h2>${plus ? 'Plus is active' : 'Add a personal cover note'}</h2><p>${plus ? 'Your unlocked cover note stays in this browser and can appear at the top of your printable packet.' : 'For $9 once, Plus adds a private personal cover note at the top of your packet. The core packet builder, backup, accessibility, and exports remain free.'}</p></div>${plus ? '<span class="plus-active">License active</span>' : '<div class="plus-actions"><a class="primary" href="https://api.sociobot.in/api/v1/products/health-visit-packet/checkout">Buy Plus — $9 once</a><button id="restore-license" class="text-button">Have a license?</button></div>'}</section></main>
  <footer><span>Health Visit Packet is a preparation tool, not medical advice.</span><span>Generated illustration · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></span></footer><dialog id="bundle-dialog"><form method="dialog" id="bundle-form"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Encrypted backup</p><h2>Choose a passphrase</h2><p>This encrypts a copy before it downloads. We cannot recover a forgotten passphrase.</p><label>Passphrase <input name="passphrase" type="password" minlength="8" autocomplete="new-password" required></label><p id="dialog-error" class="error" role="alert"></p><button class="primary" value="default">Encrypt & download</button></form></dialog><dialog id="restore-dialog"><form method="dialog" id="restore-form"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Restore packet</p><h2>Open your encrypted bundle</h2><label>Passphrase <input name="passphrase" type="password" required></label><p id="restore-error" class="error" role="alert"></p><button class="primary" value="default">Restore and replace this packet</button></form></dialog><dialog id="license-dialog"><form method="dialog" id="license-form"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Restore Plus</p><h2>Paste your license</h2><label>License token <input name="license" autocomplete="off" required></label><p id="license-error" class="error" role="alert"></p><button class="primary" value="default">Restore license</button></form></dialog>`;
  renderPacket(); bind();
}
function bindDeletes() { document.querySelectorAll<HTMLButtonElement>('.delete').forEach(b => b.onclick = () => { const kind = b.dataset.kind as 'observations'|'medications'|'questions'; const id = b.dataset.id; packet[kind] = packet[kind].filter(x => x.id !== id) as never; queueSave(); render(); announce('Entry removed.'); }); }
function bind() {
  $('#profile-form').addEventListener('input', e => { const t = e.target as HTMLInputElement; if (t.name in packet.profile) { (packet.profile as Record<string,string>)[t.name] = t.value; queueSave(); renderPacket(); } });
  const add = (id: string, fn: (d: FormData) => SourceItem | Medication | Question) => $<HTMLFormElement>(id).addEventListener('submit', e => { e.preventDefault(); const form = e.currentTarget as HTMLFormElement; const item = fn(new FormData(form)); if (id === '#observation-form') packet.observations.push(item as SourceItem); if (id === '#medication-form') packet.medications.push(item as Medication); if (id === '#question-form') packet.questions.push(item as Question); form.reset(); queueSave(); render(); announce('Added to your packet.'); });
  add('#observation-form', d => ({id:uid(),label:String(d.get('label')),value:String(d.get('value')),unit:String(d.get('unit')),source:String(d.get('source')),date:String(d.get('date')),note:String(d.get('note'))}));
  add('#medication-form', d => ({id:uid(),name:String(d.get('name')),dose:String(d.get('dose')),schedule:String(d.get('schedule')),source:String(d.get('source'))}));
  add('#question-form', d => ({id:uid(),question:String(d.get('question')),note:String(d.get('note'))}));
  $('#print').addEventListener('click', () => { announce('Opening print settings. Review the packet sheet before saving as PDF.'); window.print(); });
  $('#json-export').addEventListener('click', () => { if (!confirm('Plain JSON is readable by anyone with the file. Download it?')) return; download('health-visit-packet.json', JSON.stringify(packet, null, 2)); announce('Plain JSON downloaded.'); });
  const d = $<HTMLDialogElement>('#bundle-dialog'); $('#encrypted-export').addEventListener('click', () => d.showModal());
  $('#bundle-form').addEventListener('submit', async e => { e.preventDefault(); const pass = String(new FormData(e.currentTarget as HTMLFormElement).get('passphrase')); try { const bundle = await encryptBundle(packet, pass); download('health-visit-packet.encrypted.json', JSON.stringify(bundle)); d.close(); announce('Encrypted bundle downloaded. Keep the passphrase separately.'); } catch (err) { $('#dialog-error').textContent = err instanceof Error ? err.message : 'Could not encrypt the bundle.'; } });
  let picked: EncryptedBundle | undefined; const restore = $<HTMLDialogElement>('#restore-dialog');
  $('#import-file').addEventListener('change', async e => { const file = (e.target as HTMLInputElement).files?.[0]; if (!file) return; try { picked = JSON.parse(await file.text()) as EncryptedBundle; restore.showModal(); } catch { announce('That file could not be read as a bundle.'); } });
  $('#restore-form').addEventListener('submit', async e => { e.preventDefault(); try { const data = await decryptBundle(picked!, String(new FormData(e.currentTarget as HTMLFormElement).get('passphrase'))); if (!data || typeof data !== 'object' || (data as Packet).version !== 1) throw new Error('This bundle does not contain a valid packet.'); packet = data as Packet; queueSave(); restore.close(); render(); announce('Packet restored to this device.'); } catch (err) { $('#restore-error').textContent = err instanceof Error ? err.message : 'Could not restore that bundle.'; } });
  const licenseDialog = $<HTMLDialogElement>('#license-dialog'); document.querySelector('#restore-license')?.addEventListener('click', () => licenseDialog.showModal());
  $('#license-form').addEventListener('submit', async e => { e.preventDefault(); const token = String(new FormData(e.currentTarget as HTMLFormElement).get('license')).trim(); if (!token) return; localStorage.setItem(LICENSE_KEY, token); plus = true; licenseDialog.close(); render(); announce('License saved. Checking it in the background.'); void verifyLicense(); });
}
function route() { if (location.pathname === '/privacy' || location.pathname === '/terms') { location.href = `${location.pathname}/`; return; } }
async function verifyLicense() { const token = localStorage.getItem(LICENSE_KEY); if (!token || !navigator.onLine) return; try { const old = JSON.parse(localStorage.getItem(VERDICT_KEY) || '{}') as { checkedAt?: number }; if (old.checkedAt && Date.now() - old.checkedAt < 86400000) return; const response = await fetch(`https://api.sociobot.in/api/v1/products/health-visit-packet/verify?license=${encodeURIComponent(token)}`); const verdict = await response.json() as { valid?: boolean }; localStorage.setItem(VERDICT_KEY, JSON.stringify({ checkedAt: Date.now(), valid: verdict.valid === true })); if (!verdict.valid) { plus = false; render(); announce('This license is no longer active. Your core packet remains available.'); } } catch { /* Offline and transient failures keep the optimistic local unlock. */ } }
async function init() { route(); const query = new URLSearchParams(location.search); const returnedLicense = query.get('license'); if (returnedLicense) { localStorage.setItem(LICENSE_KEY, returnedLicense); history.replaceState({}, '', `${location.pathname}${location.hash}`); } const cached = JSON.parse(localStorage.getItem(VERDICT_KEY) || '{}') as { valid?: boolean }; plus = Boolean(localStorage.getItem(LICENSE_KEY)) && cached.valid !== false; await load(); render(); const update = () => { const e = $<HTMLElement>('#offline'); e.hidden = navigator.onLine; }; addEventListener('online', update); addEventListener('offline', update); update(); void verifyLicense(); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => {}); }
init();
